setxkbmap -option "ctrl:swapcaps"
xmodmap -e "keycode any = F20"
xcape -e "Alt_L=parenleft;Alt_R=parenright;#66=F20"
export XMODIFIERS=@im=exim
export GTK_IM_MODULE=xim
export QT_IM_MODULE=xim
export CLUTTER_IM_MODULE=xim
export _JAVA_AWT_WM_NONREPARENTING=1
feh --bg-scale ~/Dropbox/AltDesktop.jpg
#xset m 4 0
#xinput set-prop 12 'Coordinate Transformation Matrix' 1.0 0.0 0.0 0.0 1.5 0.0 0.0 0.0 1.0
#xinput set-prop 12 'Device Accel Constant Deceleration' 6
xrandr --output DP-3 --right-of DVI-I-1 --output HDMI-0 --left-of DVI-I-1
# xmodmap -e "clear lock"
#cd xstarts
#exec qtile
#python2 -c "while True:	pass"
systemctl --user start remotemouse
picom &


#sxhkd &
#terminator &
#exec bspwm
#exec startNwm
#stumpwm >.stumplog &
# sleep 2
# pulseaudio &
#sleep 5
#./startupScript
exwm-start
# exec xterm
# emacs -eval "(exwm-enable)"
# exec gnome-session
# exec awesome
