(deftheme TAB-plus-plus
  "Created 2016-09-28.")

(custom-theme-set-variables
 'TAB-plus-plus
 '(fci-rule-color "#192028")
 '(ansi-color-names-vector ["#14191f" "#d15120" "#81af34" "#deae3e" "#7e9fc9" "#a878b5" "#7e9fc9" "#dcdddd"])
 '(ansi-term-color-vector [unspecified "#14191f" "#d15120" "#81af34" "#deae3e" "#7e9fc9" "#a878b5" "#7e9fc9" "#dcdddd"]))

(custom-theme-set-faces
 'TAB-plus-plus
 '(cursor ((t (:background "#b4b4b4"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((t (:family "Sans Serif"))))
 '(escape-glyph ((t (:foreground "#a878b5" :background "#25222f"))))
 '(minibuffer-prompt ((t (:foreground "#d97a35" :background "#272122"))))
 '(region ((t (:background "#313c4d"))))
 '(shadow ((((class color grayscale) (min-colors 88) (background light)) (:foreground "grey50")) (((class color grayscale) (min-colors 88) (background dark)) (:foreground "grey70")) (((class color) (min-colors 8) (background light)) (:foreground "green")) (((class color) (min-colors 8) (background dark)) (:foreground "yellow"))))
 '(secondary-selection ((((class color) (min-colors 88) (background light)) (:background "yellow1")) (((class color) (min-colors 88) (background dark)) (:background "SkyBlue4")) (((class color) (min-colors 16) (background light)) (:background "yellow")) (((class color) (min-colors 16) (background dark)) (:background "SkyBlue4")) (((class color) (min-colors 8)) (:foreground "black" :background "cyan")) (t (:inverse-video t))))
 '(trailing-whitespace ((t (:background "Firebrick"))))
 '(font-lock-builtin-face ((t (:foreground "#deae3e" :background "#2a2921"))))
 '(font-lock-comment-delimiter-face ((default (:inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((t (:foreground "#716d73" :background "#181d23" :italic t))))
 '(font-lock-constant-face ((t (:foreground "#a878b5" :background "#25222f"))))
 '(font-lock-doc-face ((t (:foreground "#878289" :background "#181d23"))))
 '(font-lock-function-name-face ((t (:foreground "#d15120" :background "#2a1f1f"))))
 '(font-lock-keyword-face ((t (:foreground "#d97a35" :background "#272122"))))
 '(font-lock-negation-char-face ((t (:foreground "#deae3e" :background "#2a2921"))))
 '(font-lock-preprocessor-face ((t (:foreground "#d97a35" :background "#272122"))))
 '(font-lock-regexp-grouping-backslash ((t (:inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "#81af34" :background "#1a2321"))))
 '(font-lock-type-face ((t (:foreground "#b23f1e" :background "#251c1e" :bold nil))))
 '(font-lock-variable-name-face ((t (:foreground "#7e9fc9" :background "#1e252f"))))
 '(font-lock-warning-face ((t (:foreground "#b23f1e" :background "#251c1e"))))
 '(button ((t (:inherit (link)))))
 '(link ((t (:foreground "#7e9fc9" :background "#1e252f"))))
 '(link-visited ((default (:inherit (link))) (((class color) (background light)) (:foreground "magenta4")) (((class color) (background dark)) (:foreground "violet"))))
 '(fringe ((t (:foreground "#716d73" :background "#181d23"))))
 '(header-line ((default (:inherit (mode-line))) (((type tty)) (:underline (:color foreground-color :style line) :inverse-video nil)) (((class color grayscale) (background light)) (:box nil :foreground "grey20" :background "grey90")) (((class color grayscale) (background dark)) (:box nil :foreground "grey90" :background "grey20")) (((class mono) (background light)) (:underline (:color foreground-color :style line) :box nil :inverse-video nil :foreground "black" :background "white")) (((class mono) (background dark)) (:underline (:color foreground-color :style line) :box nil :inverse-video nil :foreground "white" :background "black"))))
 '(tooltip ((((class color)) (:inherit (variable-pitch) :foreground "black" :background "lightyellow")) (t (:inherit (variable-pitch)))))
 '(mode-line ((t (:foreground "#7e9fc9" :background "#1b333e"))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((((class color) (min-colors 88)) (:box (:line-width 2 :color "grey40" :style released-button))) (t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:foreground "#365e7a" :background "#1f2730"))))
 '(isearch ((((class color) (min-colors 88) (background light)) (:foreground "lightskyblue1" :background "magenta3")) (((class color) (min-colors 88) (background dark)) (:foreground "brown4" :background "palevioletred2")) (((class color) (min-colors 16)) (:foreground "cyan1" :background "magenta4")) (((class color) (min-colors 8)) (:foreground "cyan1" :background "magenta4")) (t (:inverse-video t))))
 '(isearch-fail ((((class color) (min-colors 88) (background light)) (:background "RosyBrown1")) (((class color) (min-colors 88) (background dark)) (:background "red4")) (((class color) (min-colors 16)) (:background "red")) (((class color) (min-colors 8)) (:background "red")) (((class color grayscale)) (:foreground "grey")) (t (:inverse-video t))))
 '(lazy-highlight ((((class color) (min-colors 88) (background light)) (:background "paleturquoise")) (((class color) (min-colors 88) (background dark)) (:background "paleturquoise4")) (((class color) (min-colors 16)) (:background "turquoise3")) (((class color) (min-colors 8)) (:background "turquoise3")) (t (:underline (:color foreground-color :style line)))))
 '(match ((((class color) (min-colors 88) (background light)) (:background "yellow1")) (((class color) (min-colors 88) (background dark)) (:background "RoyalBlue3")) (((class color) (min-colors 8) (background light)) (:foreground "black" :background "yellow")) (((class color) (min-colors 8) (background dark)) (:foreground "white" :background "blue")) (((type tty) (class mono)) (:inverse-video t)) (t (:background "gray"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch)))))
 '(hl-line ((t (:background "#1b2129"))))
 '(error ((t (:foreground "#c6350b"))))
 '(vertical-border ((t (:background "#14191f" :foreground "#242d38"))))
 '(show-paren-match ((t (:foreground "#d97a35" :background "#272122"))))
 '(show-paren-mismatch ((t (:foreground "#251c1e" :background "#b23f1e"))))
 '(ido-only-match ((t (:foreground "#81af34" :background "#1a2321"))))
 '(ido-subdir ((t (:foreground "#a878b5" :background "#25222f"))))
 '(org-date ((t (:foreground "#a878b5" :background "#25222f"))))
 '(org-done ((t (:foreground "#81af34" :background "#1a2321"))))
 '(org-hide ((t (:foreground "#2a3441" :background "#181d23"))))
 '(org-link ((t (:foreground "#7e9fc9" :background "#1e252f"))))
 '(org-todo ((t (:foreground "#d15120" :background "#2a1f1f"))))
 '(slime-highlight-edits-face ((t (:background "black"))))
 '(default ((t (:background "#14191f" :foreground "#dcdddd")))))

(provide-theme 'TAB-plus-plus)
