# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("accessibility.typeaheadfind.autostart", false);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 4);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.link.open_newwindow.restriction", 0);
user_pref("browser.migration.version", 29);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.search.countryCode", "US");
user_pref("browser.search.region", "US");
user_pref("browser.slowStartup.averageTime", 1858);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20150702232110");
user_pref("browser.startup.homepage_override.mstone", "39.0");
user_pref("browser.tabs.autoHide", false);
user_pref("browser.toolbarbuttons.introduced.pocket-button", true);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"PanelUI-contents\":[\"edit-controls\",\"zoom-controls\",\"new-window-button\",\"privatebrowsing-button\",\"save-page-button\",\"print-button\",\"history-panelmenu\",\"fullscreen-button\",\"find-button\",\"preferences-button\",\"add-ons-button\",\"developer-button\"],\"addon-bar\":[\"addonbar-closebutton\",\"status-bar\"],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"urlbar-container\",\"search-container\",\"bookmarks-menu-button\",\"pocket-button\",\"downloads-button\",\"home-button\",\"loop-button\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"dactyl-addon-bar\":[\"dactyl-status-bar\"]},\"seen\":[],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\",\"dactyl-addon-bar\"],\"currentVersion\":4,\"newElementCount\":0}");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1437021630478");
user_pref("datareporting.policy.firstRunTime", "1436935230478");
user_pref("datareporting.sessions.current.activeTicks", 3);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 1748);
user_pref("datareporting.sessions.current.main", 43);
user_pref("datareporting.sessions.current.sessionRestored", 1874);
user_pref("datareporting.sessions.current.startTime", "1436935293633");
user_pref("datareporting.sessions.current.totalTime", 15);
user_pref("datareporting.sessions.currentIndex", 1);
user_pref("datareporting.sessions.previous.0", "{\"s\":1436935202163,\"a\":0,\"t\":28,\"c\":false,\"m\":27653,\"fp\":-1,\"sr\":-1}");
user_pref("dom.mozApps.used", true);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{\"pentadactyl@dactyl.googlecode.com\":{\"version\":\"1.2pre\",\"type\":\"extension\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/pentadactyl@dactyl.googlecode.com\",\"multiprocessCompatible\":false}}");
user_pref("extensions.dactyl.cacheFlushCheck", "1.2pre");
user_pref("extensions.dactyl.cleanup.option.guioptions", "rbsT");
user_pref("extensions.dactyl.didSanitizeOnShutdown", false);
user_pref("extensions.dactyl.first-run", false);
user_pref("extensions.dactyl.lastVersion", "1.2pre");
user_pref("extensions.dactyl.original.accessibility.typeaheadfind", false);
user_pref("extensions.dactyl.original.accessibility.typeaheadfind.autostart", true);
user_pref("extensions.dactyl.original.accessibility.typeaheadfind.enablesound", true);
user_pref("extensions.dactyl.original.browser.link.open_newwindow", 3);
user_pref("extensions.dactyl.original.browser.link.open_newwindow.restriction", 2);
user_pref("extensions.dactyl.original.browser.tabs.drawInTitlebar", false);
user_pref("extensions.dactyl.original.browser.tabs.loadBookmarksInBackground", false);
user_pref("extensions.dactyl.original.browser.tabs.loadDivertedInBackground", false);
user_pref("extensions.dactyl.original.browser.tabs.loadInBackground", true);
user_pref("extensions.dactyl.original.layout.scrollbar.side", 0);
user_pref("extensions.dactyl.saved.accessibility.typeaheadfind", false);
user_pref("extensions.dactyl.saved.accessibility.typeaheadfind.autostart", false);
user_pref("extensions.dactyl.saved.accessibility.typeaheadfind.enablesound", true);
user_pref("extensions.dactyl.saved.browser.link.open_newwindow", 3);
user_pref("extensions.dactyl.saved.browser.link.open_newwindow.restriction", 0);
user_pref("extensions.dactyl.saved.browser.tabs.autoHide", false);
user_pref("extensions.dactyl.saved.browser.tabs.drawInTitlebar", false);
user_pref("extensions.dactyl.saved.browser.tabs.loadBookmarksInBackground", false);
user_pref("extensions.dactyl.saved.browser.tabs.loadDivertedInBackground", false);
user_pref("extensions.dactyl.saved.browser.tabs.loadInBackground", true);
user_pref("extensions.dactyl.saved.layout.scrollbar.side", 2);
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:39.0");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "39.0");
user_pref("extensions.lastPlatformVersion", "39.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.xpiState", "{\"app-global\":{\"pentadactyl@dactyl.googlecode.com\":{\"d\":\"/usr/lib/firefox/browser/extensions/pentadactyl@dactyl.googlecode.com\",\"e\":true,\"v\":\"1.2pre\",\"st\":1436502628000,\"mt\":1436502626000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"39.0\",\"st\":1436934914000,\"mt\":1435880765000}}}");
user_pref("gecko.buildID", "20150702232110");
user_pref("gecko.mstone", "39.0");
user_pref("layout.scrollbar.side", 2);
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1436935293);
user_pref("toolkit.telemetry.previousBuildID", "20150702232110");
