(deftheme LCARS
  "Created 2015-12-19.")

(custom-theme-set-faces
 'LCARS
 '(cursor ((t (:background "#FF9900" :foreground "#fdf6e3" :inverse-video t))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((t (:family "Sans Serif"))))
 '(escape-glyph ((t (:foreground "#6c71c4"))))
 '(minibuffer-prompt ((t (:foreground "#657b83"))))
 '(highlight ((t (:background "#331111"))))
 '(region ((t (:background "#586e75" :foreground "#fdf6e3"))))
 '(shadow ((t (:foreground "#93a1a1"))))
 '(secondary-selection ((t (:background "#eee8d5"))))
 '(trailing-whitespace ((t (:background "#93a1a1"))))
 '(font-lock-builtin-face ((t (:foreground "#657b83" :slant normal :weight bold))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#93a1a1" :slant normal))))
 '(font-lock-comment-face ((t (:foreground "#93a1a1"))))
 '(font-lock-constant-face ((t (:foreground "#9999FF" :weight bold))))
 '(font-lock-doc-face ((t (:foreground "#CC99CC" :slant normal))))
 '(font-lock-function-name-face ((t (:foreground "#9999FF"))))
 '(font-lock-keyword-face ((t (:foreground "#859900" :weight bold))))
 '(font-lock-negation-char-face ((t (:foreground "#b58900" :weight bold))))
 '(font-lock-preprocessor-face ((t (:foreground "#9999FF"))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#859900" :weight bold))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#b58900" :weight bold))))
 '(font-lock-string-face ((t (:foreground "#9999CC"))))
 '(font-lock-type-face ((t (:foreground "#b58900"))))
 '(font-lock-variable-name-face ((t (:foreground "#268bd2"))))
 '(font-lock-warning-face ((t (:inherit error :weight bold))))
 '(button ((t (:underline t))))
 '(link ((t (:foreground "#b58900" :underline t :weight bold))))
 '(link-visited ((t (:foreground "#b58900" :underline t :weight normal))))
 '(fringe ((t (:background "#fdf6e3" :foreground "#93a1a1"))))
 '(header-line ((t (:inherit mode-line :background "grey90" :foreground "grey20" :box nil))))
 '(tooltip ((t (:inherit variable-pitch :background "#DEB542" :foreground "#7B6000"))))
 '(mode-line ((t (:background "#eee8d5" :foreground "#657b83" :box (:line-width 1 :color "#657b83")))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((t (:box (:line-width 2 :color "grey40" :style released-button)))))
 '(mode-line-inactive ((t (:background "#fdf6e3" :foreground "#93a1a1" :box (:line-width 1 :color "#93a1a1")))))
 '(isearch ((t (:background "#d33682" :foreground "#fdf6e3" :weight normal))))
 '(isearch-fail ((t (:background "#fdf6e3" :foreground "#dc322f" :weight bold))))
 '(lazy-highlight ((t (:background "#b58900" :foreground "#fdf6e3" :weight normal))))
 '(match ((t (:background "#eee8d5" :foreground "#586e75" :weight bold))))
 '(next-error ((t (:inherit region))))
 '(query-replace ((t (:inherit isearch))))
 '(default ((t (:inherit nil :stipple nil :background "#000000" :foreground "#FF9966" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 105 :width normal :foundry "unknown" :family "DejaVu Sans Mono")))))

(provide-theme 'LCARS)
